### ISSUE TITLE
Have you ever tested this model on a real vehicle? &  How can I change from single agent prediction to multi agent prediction?

### ISSUE THREAD

**Issue by han1222** [nachiket92/PGP#12]
Hi, thank you so much for sharing great work.

I have some questions.

1. Have you ever tested this model on a real vehicle?
If a model trained using data sampled at 2 Hz is loaded on a real test vehicle, real-time performance cannot be guaranteed. Is there any recommended method to solve this problem?

2. How can I change from single agent prediction to multi agent prediction?
I wonder if it can be easily changed or if another process is required.
If not, do you have any plans to do this?

Thanks for your time.

**Comment by nachiket92** [comment]
Hi, 

1. The 2 Hz sampling frequency was chosen to match the sampling frequency in nuScenes. The simplest fix would be to train the model with trajectories sampled at a higher frequency. Also, a model trained with data sampled at 2 Hz _can_ be deployed real-time by simply down sampling the past trajectories from your multi-object tracker. For example, say the tracker operates at 10 Hz and we have tracks for the past 2 seconds. We can simply downsample the trajectories from length 20 to length 4. Inference can still run at 10 Hz.        

2. Extending the model to the multi-agent setting would take some work. I might work on this in the future. I'll keep you posted!

**Comment by han1222** [comment]
Thank you for your quick reply.

As your opinion, it would be better to train using 10Hz sampled data.

In the case of a model trained with 2Hz sample data, even if tracker operates at 10Hz and downsample the trajectories from length 20 frame to length  4 frame, 2 seconds of history  information must be inserted to model, so the updated information is considered to be 2 seconds + @ (model inference time).  Is it right ? If I'm wrong, please point it out.

To improve this, what do you think about calculating by putting it in a queue and updating only 1 out of 4 frames?
In this case, the inference speed is likely to increase, but it is unlikely to respond quickly to the given past information. If you have any insight on how to solve this, I would appreciate it if you could share it.

**Comment by nachiket92** [comment]
It doesn't matter what sampling rate the model is trained on. You'll be able to run inference at the model's inference speed.

Let's say your tracker is outputting values at 10 Hz, and you want to run inference every 0.1 seconds. You'll use the past 20 values at the current prediction step. 0.1 seconds later, you'll just need to update the past trajectories with the newest tracker output, and drop the oldest one. If your model was trained using a lower sampling rate, you can downsample this set of tracker outputs.  

Your tracking and prediction models will run in parallel - we don't need to wait for 2 seconds + prediction inference time for every step. 

Hope this makes sense. I'm closing this issue since this is a broader discussion than just the code in this repository. I'll be happy to continue the discussion though.
